version: 2

models:
  - name: woody_female_costars
    description: "Model reveals the actress with most appearances with Woody Harrelson"
    columns:
      - name: actress_name
        description: "Name of actress"
        tests:
          - not_null
      - name: number_of_appearances
        description: "Number of Appearances with Woody Harrelson"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
