version: 2

models:
  - name: woody_female_costars
    description: "Model reveals the actress with more than 1 appearances with Woody Harrelson"
    columns:
      - name: actor
        description: "Name of actor"
        tests:
          - not_null
      - name: appearances_with_woody
        description: "Number of Appearances with Woody Harrelson"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
