name: 'src'
version: '1.0.0'
config-version: 2

profile: 'src'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]

models:
  src:
    mart:
      +materialized: table
    staging:
      +materialized: table

seeds:
  src: 
    netflix_titles:
      column_types:
        show_id: string
        type: string
        title: string
        director: string
        cast: string
        country: string
        date_added: string
        release_year: integer
        rating: string
        duration: string
        listed_in: string
        description: string
