version: 2

models:
  - name: year_tv_increase
    description: "Model reveals the year with the greatest YOY increase For TV shows"
    columns:
      - name: release_year
        description: "Year of Release"
        tests:
          - not_null
      - name: number_tv_releases
        description: "Number of Releases for Current Year"
        tests:
          - not_null
      - name: last_year_releases
        description: "Previous Number of Releases"
        tests:
          - not_null
      - name: percent_increase
        description: "Percentage of Year over Year increase"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
